name: olxad
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.1.0
  flutter_svg: ^2.2.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.2
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  gif: ^2.3.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_otp_text_field: ^1.5.1+1

  # Responsive utility
  # flutter_screenutil provides .w, .h, .sp helpers. Added here under flutter key to keep simple.
  # The package will also be resolved by pub; if your project lists dependencies at top-level, move it there.
  # Using version that is compatible with Flutter 3+/Dart 3+.
  # flutter_screenutil: ^5.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/gif/

flutter_native_splash:
  color: "#FFFFFF"   # pure white background
  android: true
  ios: true
  image: null

  android_12:
    color: "#FFFFFF"
    image: null
    icon_background_color: "#FFFFFF"

